// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mwyajdydbolxuhvwzghj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im13eWFqZHlkYm9seHVodnd6Z2hqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAxMzYzNTEsImV4cCI6MjA2NTcxMjM1MX0.rcCEiz5hoIixxA8uKB--pPOf5vH7Myraz6sb-uPmy3U";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);